server:
  port: 8083

spring:
  application:
    name: auth-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gamegame?serverTimezone=Asia/Seoul
    username: root
    password: Jesuslove1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    header: Authorization
    prefix: Bearer
    tokenExpirationTime: 727380891
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
