version: '3.8'

services:
  eureka-server:
    image: quokkabong95/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - msa-network

  api-gateway:
    image: quokkabong95/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_MAIN_WEB_APPLICATION_TYPE=reactive
      - SPRING_APPLICATION_NAME=gateway-service
      - SPRING_JWT_HEADER=Authorization
      - SPRING_JWT_PREFIX=Bearer
      - SPRING_JWT_TOKEN_EXPIRATION_TIME=727380891
      - SPRING_JWT_SECRET=c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://3.37.198.42:8761/eureka/
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
    networks:
      - msa-network

  auth-service:
    image: quokkabong95/auth-service:latest
    container_name: auth-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://13.125.97.10:3306/gamegameappDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_HIGHLIGHT_SQL=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_JWT_HEADER=Authorization
      - SPRING_JWT_PREFIX=Bearer
      - SPRING_JWT_ACCESS_EXPIRATION=727380891
      - SPRING_JWT_SECRET=c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://3.37.198.42:8761/eureka/
    networks:
      - msa-network
  team-service:
    image: quokkabong95/resume-service:latest
    container_name: resume-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=team-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://13.125.97.10:3306/gamegameappDB
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_HIGHLIGHT_SQL=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://3.37.198.42:8761/eureka/
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge