server:
  port: 19093


spring:
  application:
    name: team-service

  datasource:
    url: jdbc:mysql://13.125.97.10:3306/gamegameappDB
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql ??
        format_sql: true # SQL ? ???? ??
        highlight_sql: true # SQL ? ? ??


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/