server:
  port: 19093


spring:
  application:
    name: team-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Jesuslove1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sql ??
        format_sql: true # SQL ? ???? ??
        highlight_sql: true # SQL ? ? ??


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/