server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

  jwt:
    header: Authorization
    prefix: Bearer
    tokenExpirationTime: 727380891
    secret: c3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwtc3ByaW5nYm9vdC1qd3QtdHV0b3JpYWwK

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
