server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://3.37.198.42:8761/eureka/

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    enable-self-preservation: true

